# coding=utf-8
# *** WARNING: this file was generated by the Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from .. import _utilities
# Export this package's modules as members:
from ._enums import *
from .container_group import *
from .get_container_group import *
from ._inputs import *
from . import outputs

# Make subpackages available:
v20170801preview = _utilities.lazy_import('pulumi_azure_native.containerinstance.v20170801preview')
v20171001preview = _utilities.lazy_import('pulumi_azure_native.containerinstance.v20171001preview')
v20171201preview = _utilities.lazy_import('pulumi_azure_native.containerinstance.v20171201preview')
v20180201preview = _utilities.lazy_import('pulumi_azure_native.containerinstance.v20180201preview')
v20180401 = _utilities.lazy_import('pulumi_azure_native.containerinstance.v20180401')
v20180601 = _utilities.lazy_import('pulumi_azure_native.containerinstance.v20180601')
v20180901 = _utilities.lazy_import('pulumi_azure_native.containerinstance.v20180901')
v20181001 = _utilities.lazy_import('pulumi_azure_native.containerinstance.v20181001')
v20191201 = _utilities.lazy_import('pulumi_azure_native.containerinstance.v20191201')
v20201101 = _utilities.lazy_import('pulumi_azure_native.containerinstance.v20201101')
v20210301 = _utilities.lazy_import('pulumi_azure_native.containerinstance.v20210301')
