# coding=utf-8
# *** WARNING: this file was generated by the Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from .. import _utilities
# Export this package's modules as members:
from .get_notebook_proxy import *
from .list_notebook_proxy_credentials import *
from .notebook_proxy import *

# Make subpackages available:
v20191011preview = _utilities.lazy_import('pulumi_azure_native.notebooks.v20191011preview')

def _register_module():
    import pulumi
    from .. import _utilities


    class Module(pulumi.runtime.ResourceModule):
        _version = _utilities.get_semver_version()

        def version(self):
            return Module._version

        def construct(self, name: str, typ: str, urn: str) -> pulumi.Resource:
            if typ == "azure-native:notebooks:NotebookProxy":
                return NotebookProxy(name, pulumi.ResourceOptions(urn=urn))
            else:
                raise Exception(f"unknown resource type {typ}")


    _module_instance = Module()
    pulumi.runtime.register_resource_module("azure-native", "notebooks", _module_instance)

_register_module()
