// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package latest

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi-azure-native/sdk/go/azure"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "azure-native:insights/latest:ActionGroup":
		r = &ActionGroup{}
	case "azure-native:insights/latest:ActivityLogAlert":
		r = &ActivityLogAlert{}
	case "azure-native:insights/latest:AlertRule":
		r = &AlertRule{}
	case "azure-native:insights/latest:AnalyticsItem":
		r = &AnalyticsItem{}
	case "azure-native:insights/latest:AutoscaleSetting":
		r = &AutoscaleSetting{}
	case "azure-native:insights/latest:Component":
		r = &Component{}
	case "azure-native:insights/latest:ComponentCurrentBillingFeature":
		r = &ComponentCurrentBillingFeature{}
	case "azure-native:insights/latest:ExportConfiguration":
		r = &ExportConfiguration{}
	case "azure-native:insights/latest:Favorite":
		r = &Favorite{}
	case "azure-native:insights/latest:LogProfile":
		r = &LogProfile{}
	case "azure-native:insights/latest:MetricAlert":
		r = &MetricAlert{}
	case "azure-native:insights/latest:MyWorkbook":
		r = &MyWorkbook{}
	case "azure-native:insights/latest:ProactiveDetectionConfiguration":
		r = &ProactiveDetectionConfiguration{}
	case "azure-native:insights/latest:ScheduledQueryRule":
		r = &ScheduledQueryRule{}
	case "azure-native:insights/latest:WebTest":
		r = &WebTest{}
	case "azure-native:insights/latest:Workbook":
		r = &Workbook{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

func init() {
	version, err := azure.PkgVersion()
	if err != nil {
		fmt.Println("failed to determine package version. defaulting to v1: %v", err)
	}
	pulumi.RegisterResourceModule(
		"azure-native",
		"insights/latest",
		&module{version},
	)
}
