# coding=utf-8
# *** WARNING: this file was generated by the Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from .. import _utilities
# Export this package's modules as members:
from ._enums import *
from .addon import *
from .bandwidth_schedule import *
from .container import *
from .device import *
from .get_addon import *
from .get_bandwidth_schedule import *
from .get_container import *
from .get_device import *
from .get_device_extended_information import *
from .get_monitoring_config import *
from .get_order import *
from .get_role import *
from .get_share import *
from .get_storage_account import *
from .get_storage_account_credential import *
from .get_trigger import *
from .get_user import *
from .list_order_dc_access_code import *
from .monitoring_config import *
from .order import *
from .role import *
from .share import *
from .storage_account import *
from .storage_account_credential import *
from .trigger import *
from .user import *
from ._inputs import *
from . import outputs

# Make subpackages available:
v20190301 = _utilities.lazy_import('pulumi_azure_native.databoxedge.v20190301')
v20190701 = _utilities.lazy_import('pulumi_azure_native.databoxedge.v20190701')
v20190801 = _utilities.lazy_import('pulumi_azure_native.databoxedge.v20190801')
v20200501preview = _utilities.lazy_import('pulumi_azure_native.databoxedge.v20200501preview')
v20200901 = _utilities.lazy_import('pulumi_azure_native.databoxedge.v20200901')
v20200901preview = _utilities.lazy_import('pulumi_azure_native.databoxedge.v20200901preview')
v20201201 = _utilities.lazy_import('pulumi_azure_native.databoxedge.v20201201')
v20210201preview = _utilities.lazy_import('pulumi_azure_native.databoxedge.v20210201preview')
