# coding=utf-8
# *** WARNING: this file was generated by the Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from .. import _utilities
# Export this package's modules as members:
from ._enums import *
from .budget import *
from .get_budget import *
from ._inputs import *
from . import outputs

# Make subpackages available:
v20171230preview = _utilities.lazy_import('pulumi_azure_native.consumption.v20171230preview')
v20180131 = _utilities.lazy_import('pulumi_azure_native.consumption.v20180131')
v20180331 = _utilities.lazy_import('pulumi_azure_native.consumption.v20180331')
v20180630 = _utilities.lazy_import('pulumi_azure_native.consumption.v20180630')
v20180831 = _utilities.lazy_import('pulumi_azure_native.consumption.v20180831')
v20181001 = _utilities.lazy_import('pulumi_azure_native.consumption.v20181001')
v20190101 = _utilities.lazy_import('pulumi_azure_native.consumption.v20190101')
v20190401preview = _utilities.lazy_import('pulumi_azure_native.consumption.v20190401preview')
v20190501 = _utilities.lazy_import('pulumi_azure_native.consumption.v20190501')
v20190501preview = _utilities.lazy_import('pulumi_azure_native.consumption.v20190501preview')
v20190601 = _utilities.lazy_import('pulumi_azure_native.consumption.v20190601')
v20191001 = _utilities.lazy_import('pulumi_azure_native.consumption.v20191001')
v20191101 = _utilities.lazy_import('pulumi_azure_native.consumption.v20191101')
