// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package latest

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi-azure-native/sdk/go/azure"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "azure-native:sql/latest:DataMaskingPolicy":
		r = &DataMaskingPolicy{}
	case "azure-native:sql/latest:Database":
		r = &Database{}
	case "azure-native:sql/latest:DatabaseThreatDetectionPolicy":
		r = &DatabaseThreatDetectionPolicy{}
	case "azure-native:sql/latest:DisasterRecoveryConfiguration":
		r = &DisasterRecoveryConfiguration{}
	case "azure-native:sql/latest:ElasticPool":
		r = &ElasticPool{}
	case "azure-native:sql/latest:FirewallRule":
		r = &FirewallRule{}
	case "azure-native:sql/latest:GeoBackupPolicy":
		r = &GeoBackupPolicy{}
	case "azure-native:sql/latest:Server":
		r = &Server{}
	case "azure-native:sql/latest:ServerAzureADAdministrator":
		r = &ServerAzureADAdministrator{}
	case "azure-native:sql/latest:ServerCommunicationLink":
		r = &ServerCommunicationLink{}
	case "azure-native:sql/latest:TransparentDataEncryption":
		r = &TransparentDataEncryption{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

func init() {
	version, err := azure.PkgVersion()
	if err != nil {
		fmt.Println("failed to determine package version. defaulting to v1: %v", err)
	}
	pulumi.RegisterResourceModule(
		"azure-native",
		"sql/latest",
		&module{version},
	)
}
