# coding=utf-8
# *** WARNING: this file was generated by the Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from .. import _utilities
# Export this package's modules as members:
from ._enums import *
from .app import *
from .get_app import *
from ._inputs import *
from . import outputs

# Make subpackages available:
v20170701privatepreview = _utilities.lazy_import('pulumi_azure_native.iotcentral.v20170701privatepreview')
v20180901 = _utilities.lazy_import('pulumi_azure_native.iotcentral.v20180901')

def _register_module():
    import pulumi
    from .. import _utilities


    class Module(pulumi.runtime.ResourceModule):
        _version = _utilities.get_semver_version()

        def version(self):
            return Module._version

        def construct(self, name: str, typ: str, urn: str) -> pulumi.Resource:
            if typ == "azure-native:iotcentral:App":
                return App(name, pulumi.ResourceOptions(urn=urn))
            else:
                raise Exception(f"unknown resource type {typ}")


    _module_instance = Module()
    pulumi.runtime.register_resource_module("azure-native", "iotcentral", _module_instance)

_register_module()
