# coding=utf-8
# *** WARNING: this file was generated by the Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from .. import _utilities
# Export this package's modules as members:
from ._enums import *
from .file import *
from .get_file import *
from .get_project import *
from .get_service import *
from .get_task import *
from .project import *
from .service import *
from .task import *
from ._inputs import *
from . import outputs

# Make subpackages available:
v20171115preview = _utilities.lazy_import('pulumi_azure_native.datamigration.v20171115preview')
v20180315preview = _utilities.lazy_import('pulumi_azure_native.datamigration.v20180315preview')
v20180331preview = _utilities.lazy_import('pulumi_azure_native.datamigration.v20180331preview')
v20180419 = _utilities.lazy_import('pulumi_azure_native.datamigration.v20180419')
v20180715preview = _utilities.lazy_import('pulumi_azure_native.datamigration.v20180715preview')
