# coding=utf-8
# *** WARNING: this file was generated by the Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from .. import _utilities
# Export this package's modules as members:
from ._enums import *
from .get_workspace_collection import *
from .list_workspace_collection_access_keys import *
from .workspace_collection import *
from ._inputs import *
from . import outputs

# Make subpackages available:
v20160129 = _utilities.lazy_import('pulumi_azure_native.powerbi.v20160129')
