// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package latest

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi-azure-native/sdk/go/azure"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "azure-native:web/latest:AppServiceEnvironment":
		r = &AppServiceEnvironment{}
	case "azure-native:web/latest:AppServiceEnvironmentPrivateEndpointConnection":
		r = &AppServiceEnvironmentPrivateEndpointConnection{}
	case "azure-native:web/latest:AppServicePlan":
		r = &AppServicePlan{}
	case "azure-native:web/latest:AppServicePlanRouteForVnet":
		r = &AppServicePlanRouteForVnet{}
	case "azure-native:web/latest:Certificate":
		r = &Certificate{}
	case "azure-native:web/latest:Connection":
		r = &Connection{}
	case "azure-native:web/latest:ConnectionGateway":
		r = &ConnectionGateway{}
	case "azure-native:web/latest:CustomApi":
		r = &CustomApi{}
	case "azure-native:web/latest:StaticSite":
		r = &StaticSite{}
	case "azure-native:web/latest:StaticSiteCustomDomain":
		r = &StaticSiteCustomDomain{}
	case "azure-native:web/latest:StaticSitePrivateEndpointConnection":
		r = &StaticSitePrivateEndpointConnection{}
	case "azure-native:web/latest:StaticSiteUserProvidedFunctionAppForStaticSite":
		r = &StaticSiteUserProvidedFunctionAppForStaticSite{}
	case "azure-native:web/latest:StaticSiteUserProvidedFunctionAppForStaticSiteBuild":
		r = &StaticSiteUserProvidedFunctionAppForStaticSiteBuild{}
	case "azure-native:web/latest:WebApp":
		r = &WebApp{}
	case "azure-native:web/latest:WebAppApplicationSettings":
		r = &WebAppApplicationSettings{}
	case "azure-native:web/latest:WebAppApplicationSettingsSlot":
		r = &WebAppApplicationSettingsSlot{}
	case "azure-native:web/latest:WebAppAuthSettings":
		r = &WebAppAuthSettings{}
	case "azure-native:web/latest:WebAppAuthSettingsSlot":
		r = &WebAppAuthSettingsSlot{}
	case "azure-native:web/latest:WebAppAuthSettingsV2":
		r = &WebAppAuthSettingsV2{}
	case "azure-native:web/latest:WebAppAuthSettingsV2Slot":
		r = &WebAppAuthSettingsV2Slot{}
	case "azure-native:web/latest:WebAppAzureStorageAccounts":
		r = &WebAppAzureStorageAccounts{}
	case "azure-native:web/latest:WebAppAzureStorageAccountsSlot":
		r = &WebAppAzureStorageAccountsSlot{}
	case "azure-native:web/latest:WebAppBackupConfiguration":
		r = &WebAppBackupConfiguration{}
	case "azure-native:web/latest:WebAppBackupConfigurationSlot":
		r = &WebAppBackupConfigurationSlot{}
	case "azure-native:web/latest:WebAppConnectionStrings":
		r = &WebAppConnectionStrings{}
	case "azure-native:web/latest:WebAppConnectionStringsSlot":
		r = &WebAppConnectionStringsSlot{}
	case "azure-native:web/latest:WebAppDeployment":
		r = &WebAppDeployment{}
	case "azure-native:web/latest:WebAppDeploymentSlot":
		r = &WebAppDeploymentSlot{}
	case "azure-native:web/latest:WebAppDiagnosticLogsConfiguration":
		r = &WebAppDiagnosticLogsConfiguration{}
	case "azure-native:web/latest:WebAppDomainOwnershipIdentifier":
		r = &WebAppDomainOwnershipIdentifier{}
	case "azure-native:web/latest:WebAppDomainOwnershipIdentifierSlot":
		r = &WebAppDomainOwnershipIdentifierSlot{}
	case "azure-native:web/latest:WebAppFunction":
		r = &WebAppFunction{}
	case "azure-native:web/latest:WebAppHostNameBinding":
		r = &WebAppHostNameBinding{}
	case "azure-native:web/latest:WebAppHostNameBindingSlot":
		r = &WebAppHostNameBindingSlot{}
	case "azure-native:web/latest:WebAppHybridConnection":
		r = &WebAppHybridConnection{}
	case "azure-native:web/latest:WebAppHybridConnectionSlot":
		r = &WebAppHybridConnectionSlot{}
	case "azure-native:web/latest:WebAppInstanceFunctionSlot":
		r = &WebAppInstanceFunctionSlot{}
	case "azure-native:web/latest:WebAppMetadata":
		r = &WebAppMetadata{}
	case "azure-native:web/latest:WebAppMetadataSlot":
		r = &WebAppMetadataSlot{}
	case "azure-native:web/latest:WebAppPremierAddOn":
		r = &WebAppPremierAddOn{}
	case "azure-native:web/latest:WebAppPremierAddOnSlot":
		r = &WebAppPremierAddOnSlot{}
	case "azure-native:web/latest:WebAppPrivateEndpointConnection":
		r = &WebAppPrivateEndpointConnection{}
	case "azure-native:web/latest:WebAppPrivateEndpointConnectionSlot":
		r = &WebAppPrivateEndpointConnectionSlot{}
	case "azure-native:web/latest:WebAppPublicCertificate":
		r = &WebAppPublicCertificate{}
	case "azure-native:web/latest:WebAppPublicCertificateSlot":
		r = &WebAppPublicCertificateSlot{}
	case "azure-native:web/latest:WebAppRelayServiceConnection":
		r = &WebAppRelayServiceConnection{}
	case "azure-native:web/latest:WebAppRelayServiceConnectionSlot":
		r = &WebAppRelayServiceConnectionSlot{}
	case "azure-native:web/latest:WebAppSiteExtension":
		r = &WebAppSiteExtension{}
	case "azure-native:web/latest:WebAppSiteExtensionSlot":
		r = &WebAppSiteExtensionSlot{}
	case "azure-native:web/latest:WebAppSitePushSettings":
		r = &WebAppSitePushSettings{}
	case "azure-native:web/latest:WebAppSitePushSettingsSlot":
		r = &WebAppSitePushSettingsSlot{}
	case "azure-native:web/latest:WebAppSlot":
		r = &WebAppSlot{}
	case "azure-native:web/latest:WebAppSlotConfigurationNames":
		r = &WebAppSlotConfigurationNames{}
	case "azure-native:web/latest:WebAppSourceControl":
		r = &WebAppSourceControl{}
	case "azure-native:web/latest:WebAppSourceControlSlot":
		r = &WebAppSourceControlSlot{}
	case "azure-native:web/latest:WebAppSwiftVirtualNetworkConnection":
		r = &WebAppSwiftVirtualNetworkConnection{}
	case "azure-native:web/latest:WebAppSwiftVirtualNetworkConnectionSlot":
		r = &WebAppSwiftVirtualNetworkConnectionSlot{}
	case "azure-native:web/latest:WebAppVnetConnection":
		r = &WebAppVnetConnection{}
	case "azure-native:web/latest:WebAppVnetConnectionSlot":
		r = &WebAppVnetConnectionSlot{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

func init() {
	version, err := azure.PkgVersion()
	if err != nil {
		fmt.Println("failed to determine package version. defaulting to v1: %v", err)
	}
	pulumi.RegisterResourceModule(
		"azure-native",
		"web/latest",
		&module{version},
	)
}
