// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package latest

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi-azure-native/sdk/go/azure"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "azure-native:apimanagement/latest:Api":
		r = &Api{}
	case "azure-native:apimanagement/latest:ApiDiagnostic":
		r = &ApiDiagnostic{}
	case "azure-native:apimanagement/latest:ApiDiagnosticLogger":
		r = &ApiDiagnosticLogger{}
	case "azure-native:apimanagement/latest:ApiIssue":
		r = &ApiIssue{}
	case "azure-native:apimanagement/latest:ApiIssueAttachment":
		r = &ApiIssueAttachment{}
	case "azure-native:apimanagement/latest:ApiIssueComment":
		r = &ApiIssueComment{}
	case "azure-native:apimanagement/latest:ApiManagementService":
		r = &ApiManagementService{}
	case "azure-native:apimanagement/latest:ApiOperation":
		r = &ApiOperation{}
	case "azure-native:apimanagement/latest:ApiOperationPolicy":
		r = &ApiOperationPolicy{}
	case "azure-native:apimanagement/latest:ApiPolicy":
		r = &ApiPolicy{}
	case "azure-native:apimanagement/latest:ApiRelease":
		r = &ApiRelease{}
	case "azure-native:apimanagement/latest:ApiSchema":
		r = &ApiSchema{}
	case "azure-native:apimanagement/latest:ApiTagDescription":
		r = &ApiTagDescription{}
	case "azure-native:apimanagement/latest:ApiVersionSet":
		r = &ApiVersionSet{}
	case "azure-native:apimanagement/latest:AuthorizationServer":
		r = &AuthorizationServer{}
	case "azure-native:apimanagement/latest:Backend":
		r = &Backend{}
	case "azure-native:apimanagement/latest:Cache":
		r = &Cache{}
	case "azure-native:apimanagement/latest:Certificate":
		r = &Certificate{}
	case "azure-native:apimanagement/latest:ContentItem":
		r = &ContentItem{}
	case "azure-native:apimanagement/latest:ContentType":
		r = &ContentType{}
	case "azure-native:apimanagement/latest:Diagnostic":
		r = &Diagnostic{}
	case "azure-native:apimanagement/latest:DiagnosticLogger":
		r = &DiagnosticLogger{}
	case "azure-native:apimanagement/latest:EmailTemplate":
		r = &EmailTemplate{}
	case "azure-native:apimanagement/latest:Gateway":
		r = &Gateway{}
	case "azure-native:apimanagement/latest:GatewayApiEntityTag":
		r = &GatewayApiEntityTag{}
	case "azure-native:apimanagement/latest:GatewayCertificateAuthority":
		r = &GatewayCertificateAuthority{}
	case "azure-native:apimanagement/latest:GatewayHostnameConfiguration":
		r = &GatewayHostnameConfiguration{}
	case "azure-native:apimanagement/latest:Group":
		r = &Group{}
	case "azure-native:apimanagement/latest:GroupUser":
		r = &GroupUser{}
	case "azure-native:apimanagement/latest:IdentityProvider":
		r = &IdentityProvider{}
	case "azure-native:apimanagement/latest:Logger":
		r = &Logger{}
	case "azure-native:apimanagement/latest:NamedValue":
		r = &NamedValue{}
	case "azure-native:apimanagement/latest:NotificationRecipientEmail":
		r = &NotificationRecipientEmail{}
	case "azure-native:apimanagement/latest:NotificationRecipientUser":
		r = &NotificationRecipientUser{}
	case "azure-native:apimanagement/latest:OpenIdConnectProvider":
		r = &OpenIdConnectProvider{}
	case "azure-native:apimanagement/latest:Policy":
		r = &Policy{}
	case "azure-native:apimanagement/latest:Product":
		r = &Product{}
	case "azure-native:apimanagement/latest:ProductApi":
		r = &ProductApi{}
	case "azure-native:apimanagement/latest:ProductGroup":
		r = &ProductGroup{}
	case "azure-native:apimanagement/latest:ProductPolicy":
		r = &ProductPolicy{}
	case "azure-native:apimanagement/latest:Property":
		r = &Property{}
	case "azure-native:apimanagement/latest:Subscription":
		r = &Subscription{}
	case "azure-native:apimanagement/latest:Tag":
		r = &Tag{}
	case "azure-native:apimanagement/latest:TagByApi":
		r = &TagByApi{}
	case "azure-native:apimanagement/latest:TagByOperation":
		r = &TagByOperation{}
	case "azure-native:apimanagement/latest:TagByProduct":
		r = &TagByProduct{}
	case "azure-native:apimanagement/latest:User":
		r = &User{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

func init() {
	version, err := azure.PkgVersion()
	if err != nil {
		fmt.Println("failed to determine package version. defaulting to v1: %v", err)
	}
	pulumi.RegisterResourceModule(
		"azure-native",
		"apimanagement/latest",
		&module{version},
	)
}
