# coding=utf-8
# *** WARNING: this file was generated by the Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from .. import _utilities
# Export this package's modules as members:
from ._enums import *
from .get_server_details import *
from .list_server_gateway_status import *
from .server_details import *
from ._inputs import *
from . import outputs

# Make subpackages available:
v20160516 = _utilities.lazy_import('pulumi_azure_native.analysisservices.v20160516')
v20170714 = _utilities.lazy_import('pulumi_azure_native.analysisservices.v20170714')
v20170801 = _utilities.lazy_import('pulumi_azure_native.analysisservices.v20170801')
v20170801beta = _utilities.lazy_import('pulumi_azure_native.analysisservices.v20170801beta')
