// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package latest

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi-azure-native/sdk/go/azure"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "azure-native:media/latest:AccountFilter":
		r = &AccountFilter{}
	case "azure-native:media/latest:Asset":
		r = &Asset{}
	case "azure-native:media/latest:AssetFilter":
		r = &AssetFilter{}
	case "azure-native:media/latest:ContentKeyPolicy":
		r = &ContentKeyPolicy{}
	case "azure-native:media/latest:Job":
		r = &Job{}
	case "azure-native:media/latest:LiveEvent":
		r = &LiveEvent{}
	case "azure-native:media/latest:LiveOutput":
		r = &LiveOutput{}
	case "azure-native:media/latest:MediaService":
		r = &MediaService{}
	case "azure-native:media/latest:PrivateEndpointConnection":
		r = &PrivateEndpointConnection{}
	case "azure-native:media/latest:StreamingEndpoint":
		r = &StreamingEndpoint{}
	case "azure-native:media/latest:StreamingLocator":
		r = &StreamingLocator{}
	case "azure-native:media/latest:StreamingPolicy":
		r = &StreamingPolicy{}
	case "azure-native:media/latest:Transform":
		r = &Transform{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

func init() {
	version, err := azure.PkgVersion()
	if err != nil {
		fmt.Println("failed to determine package version. defaulting to v1: %v", err)
	}
	pulumi.RegisterResourceModule(
		"azure-native",
		"media/latest",
		&module{version},
	)
}
