// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package latest

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi-azure-native/sdk/go/azure"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "azure-native:cdn/latest:AFDCustomDomain":
		r = &AFDCustomDomain{}
	case "azure-native:cdn/latest:AFDEndpoint":
		r = &AFDEndpoint{}
	case "azure-native:cdn/latest:AFDOrigin":
		r = &AFDOrigin{}
	case "azure-native:cdn/latest:AFDOriginGroup":
		r = &AFDOriginGroup{}
	case "azure-native:cdn/latest:CustomDomain":
		r = &CustomDomain{}
	case "azure-native:cdn/latest:Endpoint":
		r = &Endpoint{}
	case "azure-native:cdn/latest:Origin":
		r = &Origin{}
	case "azure-native:cdn/latest:OriginGroup":
		r = &OriginGroup{}
	case "azure-native:cdn/latest:Policy":
		r = &Policy{}
	case "azure-native:cdn/latest:Profile":
		r = &Profile{}
	case "azure-native:cdn/latest:Route":
		r = &Route{}
	case "azure-native:cdn/latest:Rule":
		r = &Rule{}
	case "azure-native:cdn/latest:RuleSet":
		r = &RuleSet{}
	case "azure-native:cdn/latest:Secret":
		r = &Secret{}
	case "azure-native:cdn/latest:SecurityPolicy":
		r = &SecurityPolicy{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

func init() {
	version, err := azure.PkgVersion()
	if err != nil {
		fmt.Println("failed to determine package version. defaulting to v1: %v", err)
	}
	pulumi.RegisterResourceModule(
		"azure-native",
		"cdn/latest",
		&module{version},
	)
}
