# coding=utf-8
# *** WARNING: this file was generated by the Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from .. import _utilities
# Export this package's modules as members:
from .get_graph_query import *
from .graph_query import *

# Make subpackages available:
v20180901preview = _utilities.lazy_import('pulumi_azure_native.resourcegraph.v20180901preview')
v20200401preview = _utilities.lazy_import('pulumi_azure_native.resourcegraph.v20200401preview')
