// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package latest

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi-azure-native/sdk/go/azure"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "azure-native:network/latest:ApplicationGateway":
		r = &ApplicationGateway{}
	case "azure-native:network/latest:ApplicationGatewayPrivateEndpointConnection":
		r = &ApplicationGatewayPrivateEndpointConnection{}
	case "azure-native:network/latest:ApplicationSecurityGroup":
		r = &ApplicationSecurityGroup{}
	case "azure-native:network/latest:AzureFirewall":
		r = &AzureFirewall{}
	case "azure-native:network/latest:BastionHost":
		r = &BastionHost{}
	case "azure-native:network/latest:ConnectionMonitor":
		r = &ConnectionMonitor{}
	case "azure-native:network/latest:CustomIPPrefix":
		r = &CustomIPPrefix{}
	case "azure-native:network/latest:DdosCustomPolicy":
		r = &DdosCustomPolicy{}
	case "azure-native:network/latest:DdosProtectionPlan":
		r = &DdosProtectionPlan{}
	case "azure-native:network/latest:DscpConfiguration":
		r = &DscpConfiguration{}
	case "azure-native:network/latest:Endpoint":
		r = &Endpoint{}
	case "azure-native:network/latest:Experiment":
		r = &Experiment{}
	case "azure-native:network/latest:ExpressRouteCircuit":
		r = &ExpressRouteCircuit{}
	case "azure-native:network/latest:ExpressRouteCircuitAuthorization":
		r = &ExpressRouteCircuitAuthorization{}
	case "azure-native:network/latest:ExpressRouteCircuitConnection":
		r = &ExpressRouteCircuitConnection{}
	case "azure-native:network/latest:ExpressRouteCircuitPeering":
		r = &ExpressRouteCircuitPeering{}
	case "azure-native:network/latest:ExpressRouteConnection":
		r = &ExpressRouteConnection{}
	case "azure-native:network/latest:ExpressRouteCrossConnectionPeering":
		r = &ExpressRouteCrossConnectionPeering{}
	case "azure-native:network/latest:ExpressRouteGateway":
		r = &ExpressRouteGateway{}
	case "azure-native:network/latest:ExpressRoutePort":
		r = &ExpressRoutePort{}
	case "azure-native:network/latest:FirewallPolicy":
		r = &FirewallPolicy{}
	case "azure-native:network/latest:FirewallPolicyRuleCollectionGroup":
		r = &FirewallPolicyRuleCollectionGroup{}
	case "azure-native:network/latest:FirewallPolicyRuleGroup":
		r = &FirewallPolicyRuleGroup{}
	case "azure-native:network/latest:FlowLog":
		r = &FlowLog{}
	case "azure-native:network/latest:FrontDoor":
		r = &FrontDoor{}
	case "azure-native:network/latest:HubRouteTable":
		r = &HubRouteTable{}
	case "azure-native:network/latest:HubVirtualNetworkConnection":
		r = &HubVirtualNetworkConnection{}
	case "azure-native:network/latest:InboundNatRule":
		r = &InboundNatRule{}
	case "azure-native:network/latest:IpAllocation":
		r = &IpAllocation{}
	case "azure-native:network/latest:IpGroup":
		r = &IpGroup{}
	case "azure-native:network/latest:LoadBalancer":
		r = &LoadBalancer{}
	case "azure-native:network/latest:LoadBalancerBackendAddressPool":
		r = &LoadBalancerBackendAddressPool{}
	case "azure-native:network/latest:LocalNetworkGateway":
		r = &LocalNetworkGateway{}
	case "azure-native:network/latest:NatGateway":
		r = &NatGateway{}
	case "azure-native:network/latest:NatRule":
		r = &NatRule{}
	case "azure-native:network/latest:NetworkExperimentProfile":
		r = &NetworkExperimentProfile{}
	case "azure-native:network/latest:NetworkInterface":
		r = &NetworkInterface{}
	case "azure-native:network/latest:NetworkInterfaceTapConfiguration":
		r = &NetworkInterfaceTapConfiguration{}
	case "azure-native:network/latest:NetworkProfile":
		r = &NetworkProfile{}
	case "azure-native:network/latest:NetworkSecurityGroup":
		r = &NetworkSecurityGroup{}
	case "azure-native:network/latest:NetworkVirtualAppliance":
		r = &NetworkVirtualAppliance{}
	case "azure-native:network/latest:NetworkWatcher":
		r = &NetworkWatcher{}
	case "azure-native:network/latest:P2sVpnGateway":
		r = &P2sVpnGateway{}
	case "azure-native:network/latest:P2sVpnServerConfiguration":
		r = &P2sVpnServerConfiguration{}
	case "azure-native:network/latest:PacketCapture":
		r = &PacketCapture{}
	case "azure-native:network/latest:Policy":
		r = &Policy{}
	case "azure-native:network/latest:PrivateDnsZoneGroup":
		r = &PrivateDnsZoneGroup{}
	case "azure-native:network/latest:PrivateEndpoint":
		r = &PrivateEndpoint{}
	case "azure-native:network/latest:PrivateLinkService":
		r = &PrivateLinkService{}
	case "azure-native:network/latest:PrivateLinkServicePrivateEndpointConnection":
		r = &PrivateLinkServicePrivateEndpointConnection{}
	case "azure-native:network/latest:PrivateZone":
		r = &PrivateZone{}
	case "azure-native:network/latest:Profile":
		r = &Profile{}
	case "azure-native:network/latest:PublicIPAddress":
		r = &PublicIPAddress{}
	case "azure-native:network/latest:PublicIPPrefix":
		r = &PublicIPPrefix{}
	case "azure-native:network/latest:RecordSet":
		r = &RecordSet{}
	case "azure-native:network/latest:Route":
		r = &Route{}
	case "azure-native:network/latest:RouteFilter":
		r = &RouteFilter{}
	case "azure-native:network/latest:RouteFilterRule":
		r = &RouteFilterRule{}
	case "azure-native:network/latest:RouteTable":
		r = &RouteTable{}
	case "azure-native:network/latest:RulesEngine":
		r = &RulesEngine{}
	case "azure-native:network/latest:SecurityPartnerProvider":
		r = &SecurityPartnerProvider{}
	case "azure-native:network/latest:SecurityRule":
		r = &SecurityRule{}
	case "azure-native:network/latest:ServiceEndpointPolicy":
		r = &ServiceEndpointPolicy{}
	case "azure-native:network/latest:ServiceEndpointPolicyDefinition":
		r = &ServiceEndpointPolicyDefinition{}
	case "azure-native:network/latest:Subnet":
		r = &Subnet{}
	case "azure-native:network/latest:TrafficManagerUserMetricsKey":
		r = &TrafficManagerUserMetricsKey{}
	case "azure-native:network/latest:VirtualApplianceSite":
		r = &VirtualApplianceSite{}
	case "azure-native:network/latest:VirtualHub":
		r = &VirtualHub{}
	case "azure-native:network/latest:VirtualHubBgpConnection":
		r = &VirtualHubBgpConnection{}
	case "azure-native:network/latest:VirtualHubIpConfiguration":
		r = &VirtualHubIpConfiguration{}
	case "azure-native:network/latest:VirtualHubRouteTableV2":
		r = &VirtualHubRouteTableV2{}
	case "azure-native:network/latest:VirtualNetwork":
		r = &VirtualNetwork{}
	case "azure-native:network/latest:VirtualNetworkGateway":
		r = &VirtualNetworkGateway{}
	case "azure-native:network/latest:VirtualNetworkGatewayConnection":
		r = &VirtualNetworkGatewayConnection{}
	case "azure-native:network/latest:VirtualNetworkLink":
		r = &VirtualNetworkLink{}
	case "azure-native:network/latest:VirtualNetworkPeering":
		r = &VirtualNetworkPeering{}
	case "azure-native:network/latest:VirtualNetworkTap":
		r = &VirtualNetworkTap{}
	case "azure-native:network/latest:VirtualRouter":
		r = &VirtualRouter{}
	case "azure-native:network/latest:VirtualRouterPeering":
		r = &VirtualRouterPeering{}
	case "azure-native:network/latest:VirtualWan":
		r = &VirtualWan{}
	case "azure-native:network/latest:VpnConnection":
		r = &VpnConnection{}
	case "azure-native:network/latest:VpnGateway":
		r = &VpnGateway{}
	case "azure-native:network/latest:VpnServerConfiguration":
		r = &VpnServerConfiguration{}
	case "azure-native:network/latest:VpnSite":
		r = &VpnSite{}
	case "azure-native:network/latest:WebApplicationFirewallPolicy":
		r = &WebApplicationFirewallPolicy{}
	case "azure-native:network/latest:Zone":
		r = &Zone{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

func init() {
	version, err := azure.PkgVersion()
	if err != nil {
		fmt.Println("failed to determine package version. defaulting to v1: %v", err)
	}
	pulumi.RegisterResourceModule(
		"azure-native",
		"network/latest",
		&module{version},
	)
}
