// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package latest

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi-azure-native/sdk/go/azure"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "azure-native:customerinsights/latest:Connector":
		r = &Connector{}
	case "azure-native:customerinsights/latest:ConnectorMapping":
		r = &ConnectorMapping{}
	case "azure-native:customerinsights/latest:Hub":
		r = &Hub{}
	case "azure-native:customerinsights/latest:Kpi":
		r = &Kpi{}
	case "azure-native:customerinsights/latest:Link":
		r = &Link{}
	case "azure-native:customerinsights/latest:Prediction":
		r = &Prediction{}
	case "azure-native:customerinsights/latest:Profile":
		r = &Profile{}
	case "azure-native:customerinsights/latest:Relationship":
		r = &Relationship{}
	case "azure-native:customerinsights/latest:RelationshipLink":
		r = &RelationshipLink{}
	case "azure-native:customerinsights/latest:RoleAssignment":
		r = &RoleAssignment{}
	case "azure-native:customerinsights/latest:View":
		r = &View{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

func init() {
	version, err := azure.PkgVersion()
	if err != nil {
		fmt.Println("failed to determine package version. defaulting to v1: %v", err)
	}
	pulumi.RegisterResourceModule(
		"azure-native",
		"customerinsights/latest",
		&module{version},
	)
}
