# coding=utf-8
# *** WARNING: this file was generated by the Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from .. import _utilities
# Export this package's modules as members:
from .get_support_plan_type import *
from .support_plan_type import *

# Make subpackages available:
v20170515 = _utilities.lazy_import('pulumi_azure_native.addons.v20170515')
v20180301 = _utilities.lazy_import('pulumi_azure_native.addons.v20180301')
