# coding=utf-8
# *** WARNING: this file was generated by the Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from .. import _utilities
# Export this package's modules as members:
from ._enums import *
from .commitment_plan import *
from .get_commitment_plan import *
from .get_web_service import *
from .get_workspace import *
from .list_workspace_keys import *
from .web_service import *
from .workspace import *
from ._inputs import *
from . import outputs

# Make subpackages available:
v20160401 = _utilities.lazy_import('pulumi_azure_native.machinelearning.v20160401')
v20160501preview = _utilities.lazy_import('pulumi_azure_native.machinelearning.v20160501preview')
v20170101 = _utilities.lazy_import('pulumi_azure_native.machinelearning.v20170101')
v20191001 = _utilities.lazy_import('pulumi_azure_native.machinelearning.v20191001')
