# coding=utf-8
# *** WARNING: this file was generated by the Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from .. import _utilities
# Export this package's modules as members:
from .get_sql_server import *
from .get_sql_server_registration import *
from .sql_server import *
from .sql_server_registration import *
from . import outputs

# Make subpackages available:
v20170301preview = _utilities.lazy_import('pulumi_azure_native.azuredata.v20170301preview')
v20190724preview = _utilities.lazy_import('pulumi_azure_native.azuredata.v20190724preview')
