// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package latest

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi-azure-native/sdk/go/azure"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "azure-native:providerhub/latest:DefaultRollout":
		r = &DefaultRollout{}
	case "azure-native:providerhub/latest:NotificationRegistration":
		r = &NotificationRegistration{}
	case "azure-native:providerhub/latest:OperationByProviderRegistration":
		r = &OperationByProviderRegistration{}
	case "azure-native:providerhub/latest:ProviderRegistration":
		r = &ProviderRegistration{}
	case "azure-native:providerhub/latest:ResourceTypeRegistration":
		r = &ResourceTypeRegistration{}
	case "azure-native:providerhub/latest:Skus":
		r = &Skus{}
	case "azure-native:providerhub/latest:SkusNestedResourceTypeFirst":
		r = &SkusNestedResourceTypeFirst{}
	case "azure-native:providerhub/latest:SkusNestedResourceTypeSecond":
		r = &SkusNestedResourceTypeSecond{}
	case "azure-native:providerhub/latest:SkusNestedResourceTypeThird":
		r = &SkusNestedResourceTypeThird{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

func init() {
	version, err := azure.PkgVersion()
	if err != nil {
		fmt.Println("failed to determine package version. defaulting to v1: %v", err)
	}
	pulumi.RegisterResourceModule(
		"azure-native",
		"providerhub/latest",
		&module{version},
	)
}
