# coding=utf-8
# *** WARNING: this file was generated by the Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from .. import _utilities
# Export this package's modules as members:
from .android_mam_policy_by_name import *
from .get_android_mam_policy_by_name import *
from .get_io_mam_policy_by_name import *
from .io_mam_policy_by_name import *

# Make subpackages available:
v20150114preview = _utilities.lazy_import('pulumi_azure_native.intune.v20150114preview')
v20150114privatepreview = _utilities.lazy_import('pulumi_azure_native.intune.v20150114privatepreview')
