# coding=utf-8
# *** WARNING: this file was generated by the Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from .. import _utilities
# Export this package's modules as members:
from ._enums import *
from .configuration import *
from .database import *
from .firewall_rule import *
from .get_configuration import *
from .get_database import *
from .get_firewall_rule import *
from .get_private_endpoint_connection import *
from .get_server import *
from .get_server_administrator import *
from .get_server_key import *
from .get_virtual_network_rule import *
from .private_endpoint_connection import *
from .server import *
from .server_administrator import *
from .server_key import *
from .virtual_network_rule import *
from ._inputs import *
from . import outputs

# Make subpackages available:
v20171201 = _utilities.lazy_import('pulumi_azure_native.dbforpostgresql.v20171201')
v20171201preview = _utilities.lazy_import('pulumi_azure_native.dbforpostgresql.v20171201preview')
v20180601 = _utilities.lazy_import('pulumi_azure_native.dbforpostgresql.v20180601')
v20180601privatepreview = _utilities.lazy_import('pulumi_azure_native.dbforpostgresql.v20180601privatepreview')
v20200101 = _utilities.lazy_import('pulumi_azure_native.dbforpostgresql.v20200101')
v20200101privatepreview = _utilities.lazy_import('pulumi_azure_native.dbforpostgresql.v20200101privatepreview')
v20200214preview = _utilities.lazy_import('pulumi_azure_native.dbforpostgresql.v20200214preview')
v20200214privatepreview = _utilities.lazy_import('pulumi_azure_native.dbforpostgresql.v20200214privatepreview')
v20201005privatepreview = _utilities.lazy_import('pulumi_azure_native.dbforpostgresql.v20201005privatepreview')
v20201105preview = _utilities.lazy_import('pulumi_azure_native.dbforpostgresql.v20201105preview')
