// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package latest

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi-azure-native/sdk/go/azure"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "azure-native:synapse/latest:BigDataPool":
		r = &BigDataPool{}
	case "azure-native:synapse/latest:IntegrationRuntime":
		r = &IntegrationRuntime{}
	case "azure-native:synapse/latest:IpFirewallRule":
		r = &IpFirewallRule{}
	case "azure-native:synapse/latest:Key":
		r = &Key{}
	case "azure-native:synapse/latest:PrivateEndpointConnection":
		r = &PrivateEndpointConnection{}
	case "azure-native:synapse/latest:PrivateLinkHub":
		r = &PrivateLinkHub{}
	case "azure-native:synapse/latest:SqlPool":
		r = &SqlPool{}
	case "azure-native:synapse/latest:SqlPoolSensitivityLabel":
		r = &SqlPoolSensitivityLabel{}
	case "azure-native:synapse/latest:SqlPoolTransparentDataEncryption":
		r = &SqlPoolTransparentDataEncryption{}
	case "azure-native:synapse/latest:SqlPoolVulnerabilityAssessment":
		r = &SqlPoolVulnerabilityAssessment{}
	case "azure-native:synapse/latest:SqlPoolVulnerabilityAssessmentRuleBaseline":
		r = &SqlPoolVulnerabilityAssessmentRuleBaseline{}
	case "azure-native:synapse/latest:SqlPoolWorkloadClassifier":
		r = &SqlPoolWorkloadClassifier{}
	case "azure-native:synapse/latest:SqlPoolWorkloadGroup":
		r = &SqlPoolWorkloadGroup{}
	case "azure-native:synapse/latest:Workspace":
		r = &Workspace{}
	case "azure-native:synapse/latest:WorkspaceAadAdmin":
		r = &WorkspaceAadAdmin{}
	case "azure-native:synapse/latest:WorkspaceManagedSqlServerVulnerabilityAssessment":
		r = &WorkspaceManagedSqlServerVulnerabilityAssessment{}
	case "azure-native:synapse/latest:WorkspaceSqlAadAdmin":
		r = &WorkspaceSqlAadAdmin{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

func init() {
	version, err := azure.PkgVersion()
	if err != nil {
		fmt.Println("failed to determine package version. defaulting to v1: %v", err)
	}
	pulumi.RegisterResourceModule(
		"azure-native",
		"synapse/latest",
		&module{version},
	)
}
