// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package latest

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi-azure-native/sdk/go/azure"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "azure-native:automation/latest:AutomationAccount":
		r = &AutomationAccount{}
	case "azure-native:automation/latest:Certificate":
		r = &Certificate{}
	case "azure-native:automation/latest:Connection":
		r = &Connection{}
	case "azure-native:automation/latest:ConnectionType":
		r = &ConnectionType{}
	case "azure-native:automation/latest:Credential":
		r = &Credential{}
	case "azure-native:automation/latest:DscConfiguration":
		r = &DscConfiguration{}
	case "azure-native:automation/latest:DscNodeConfiguration":
		r = &DscNodeConfiguration{}
	case "azure-native:automation/latest:JobSchedule":
		r = &JobSchedule{}
	case "azure-native:automation/latest:Module":
		r = &Module{}
	case "azure-native:automation/latest:Python2Package":
		r = &Python2Package{}
	case "azure-native:automation/latest:Runbook":
		r = &Runbook{}
	case "azure-native:automation/latest:Schedule":
		r = &Schedule{}
	case "azure-native:automation/latest:SoftwareUpdateConfigurationByName":
		r = &SoftwareUpdateConfigurationByName{}
	case "azure-native:automation/latest:SourceControl":
		r = &SourceControl{}
	case "azure-native:automation/latest:Variable":
		r = &Variable{}
	case "azure-native:automation/latest:Watcher":
		r = &Watcher{}
	case "azure-native:automation/latest:Webhook":
		r = &Webhook{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

func init() {
	version, err := azure.PkgVersion()
	if err != nil {
		fmt.Println("failed to determine package version. defaulting to v1: %v", err)
	}
	pulumi.RegisterResourceModule(
		"azure-native",
		"automation/latest",
		&module{version},
	)
}
