// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package latest

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi-azure-native/sdk/go/azure"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "azure-native:logic/latest:IntegrationAccount":
		r = &IntegrationAccount{}
	case "azure-native:logic/latest:IntegrationAccountAgreement":
		r = &IntegrationAccountAgreement{}
	case "azure-native:logic/latest:IntegrationAccountAssembly":
		r = &IntegrationAccountAssembly{}
	case "azure-native:logic/latest:IntegrationAccountBatchConfiguration":
		r = &IntegrationAccountBatchConfiguration{}
	case "azure-native:logic/latest:IntegrationAccountCertificate":
		r = &IntegrationAccountCertificate{}
	case "azure-native:logic/latest:IntegrationAccountMap":
		r = &IntegrationAccountMap{}
	case "azure-native:logic/latest:IntegrationAccountPartner":
		r = &IntegrationAccountPartner{}
	case "azure-native:logic/latest:IntegrationAccountSchema":
		r = &IntegrationAccountSchema{}
	case "azure-native:logic/latest:IntegrationAccountSession":
		r = &IntegrationAccountSession{}
	case "azure-native:logic/latest:IntegrationServiceEnvironment":
		r = &IntegrationServiceEnvironment{}
	case "azure-native:logic/latest:IntegrationServiceEnvironmentManagedApi":
		r = &IntegrationServiceEnvironmentManagedApi{}
	case "azure-native:logic/latest:RosettaNetProcessConfiguration":
		r = &RosettaNetProcessConfiguration{}
	case "azure-native:logic/latest:Workflow":
		r = &Workflow{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

func init() {
	version, err := azure.PkgVersion()
	if err != nil {
		fmt.Println("failed to determine package version. defaulting to v1: %v", err)
	}
	pulumi.RegisterResourceModule(
		"azure-native",
		"logic/latest",
		&module{version},
	)
}
