# coding=utf-8
# *** WARNING: this file was generated by the Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from .. import _utilities
# Export this package's modules as members:
from ._enums import *
from .custom_location import *
from .getcustom_location import *
from ._inputs import *
from . import outputs

# Make subpackages available:
v20200715privatepreview = _utilities.lazy_import('pulumi_azure_native.extendedlocation.v20200715privatepreview')
v20210315preview = _utilities.lazy_import('pulumi_azure_native.extendedlocation.v20210315preview')
