# coding=utf-8
# *** WARNING: this file was generated by the Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from .. import _utilities
# Export this package's modules as members:
from ._enums import *
from .digital_twin import *
from .digital_twins_endpoint import *
from .get_digital_twin import *
from .get_digital_twins_endpoint import *
from .get_private_endpoint_connection import *
from .private_endpoint_connection import *
from ._inputs import *
from . import outputs

# Make subpackages available:
v20200301preview = _utilities.lazy_import('pulumi_azure_native.digitaltwins.v20200301preview')
v20201031 = _utilities.lazy_import('pulumi_azure_native.digitaltwins.v20201031')
v20201201 = _utilities.lazy_import('pulumi_azure_native.digitaltwins.v20201201')
