# coding=utf-8
# *** WARNING: this file was generated by the Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from .. import _utilities
# Export this package's modules as members:
from .communication_service import *
from .get_communication_service import *
from .list_communication_service_keys import *
from . import outputs

# Make subpackages available:
v20200820 = _utilities.lazy_import('pulumi_azure_native.communication.v20200820')
v20200820preview = _utilities.lazy_import('pulumi_azure_native.communication.v20200820preview')
