// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package latest

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi-azure-native/sdk/go/azure"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "azure-native:devtestlab/latest:ArtifactSource":
		r = &ArtifactSource{}
	case "azure-native:devtestlab/latest:CustomImage":
		r = &CustomImage{}
	case "azure-native:devtestlab/latest:Disk":
		r = &Disk{}
	case "azure-native:devtestlab/latest:Environment":
		r = &Environment{}
	case "azure-native:devtestlab/latest:Formula":
		r = &Formula{}
	case "azure-native:devtestlab/latest:GlobalSchedule":
		r = &GlobalSchedule{}
	case "azure-native:devtestlab/latest:Lab":
		r = &Lab{}
	case "azure-native:devtestlab/latest:NotificationChannel":
		r = &NotificationChannel{}
	case "azure-native:devtestlab/latest:Policy":
		r = &Policy{}
	case "azure-native:devtestlab/latest:Schedule":
		r = &Schedule{}
	case "azure-native:devtestlab/latest:Secret":
		r = &Secret{}
	case "azure-native:devtestlab/latest:ServiceFabric":
		r = &ServiceFabric{}
	case "azure-native:devtestlab/latest:ServiceFabricSchedule":
		r = &ServiceFabricSchedule{}
	case "azure-native:devtestlab/latest:ServiceRunner":
		r = &ServiceRunner{}
	case "azure-native:devtestlab/latest:User":
		r = &User{}
	case "azure-native:devtestlab/latest:VirtualMachine":
		r = &VirtualMachine{}
	case "azure-native:devtestlab/latest:VirtualMachineSchedule":
		r = &VirtualMachineSchedule{}
	case "azure-native:devtestlab/latest:VirtualNetwork":
		r = &VirtualNetwork{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

func init() {
	version, err := azure.PkgVersion()
	if err != nil {
		fmt.Println("failed to determine package version. defaulting to v1: %v", err)
	}
	pulumi.RegisterResourceModule(
		"azure-native",
		"devtestlab/latest",
		&module{version},
	)
}
