// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package latest

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi-azure-native/sdk/go/azure"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "azure-native:storage/latest:BlobContainer":
		r = &BlobContainer{}
	case "azure-native:storage/latest:BlobContainerImmutabilityPolicy":
		r = &BlobContainerImmutabilityPolicy{}
	case "azure-native:storage/latest:BlobInventoryPolicy":
		r = &BlobInventoryPolicy{}
	case "azure-native:storage/latest:BlobServiceProperties":
		r = &BlobServiceProperties{}
	case "azure-native:storage/latest:EncryptionScope":
		r = &EncryptionScope{}
	case "azure-native:storage/latest:FileServiceProperties":
		r = &FileServiceProperties{}
	case "azure-native:storage/latest:FileShare":
		r = &FileShare{}
	case "azure-native:storage/latest:ManagementPolicy":
		r = &ManagementPolicy{}
	case "azure-native:storage/latest:ObjectReplicationPolicy":
		r = &ObjectReplicationPolicy{}
	case "azure-native:storage/latest:PrivateEndpointConnection":
		r = &PrivateEndpointConnection{}
	case "azure-native:storage/latest:Queue":
		r = &Queue{}
	case "azure-native:storage/latest:QueueServiceProperties":
		r = &QueueServiceProperties{}
	case "azure-native:storage/latest:StorageAccount":
		r = &StorageAccount{}
	case "azure-native:storage/latest:Table":
		r = &Table{}
	case "azure-native:storage/latest:TableServiceProperties":
		r = &TableServiceProperties{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

func init() {
	version, err := azure.PkgVersion()
	if err != nil {
		fmt.Println("failed to determine package version. defaulting to v1: %v", err)
	}
	pulumi.RegisterResourceModule(
		"azure-native",
		"storage/latest",
		&module{version},
	)
}
