# coding=utf-8
# *** WARNING: this file was generated by the Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from .. import _utilities
# Export this package's modules as members:
from .get_user_assigned_identity import *
from .user_assigned_identity import *

# Make subpackages available:
v20150831preview = _utilities.lazy_import('pulumi_azure_native.managedidentity.v20150831preview')
v20181130 = _utilities.lazy_import('pulumi_azure_native.managedidentity.v20181130')
