# coding=utf-8
# *** WARNING: this file was generated by the Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from .. import _utilities
# Export this package's modules as members:
from ._enums import *
from .app_service_certificate_order import *
from .app_service_certificate_order_certificate import *
from .get_app_service_certificate_order import *
from .get_app_service_certificate_order_certificate import *
from ._inputs import *
from . import outputs

# Make subpackages available:
v20150801 = _utilities.lazy_import('pulumi_azure_native.certificateregistration.v20150801')
v20180201 = _utilities.lazy_import('pulumi_azure_native.certificateregistration.v20180201')
v20190801 = _utilities.lazy_import('pulumi_azure_native.certificateregistration.v20190801')
v20200601 = _utilities.lazy_import('pulumi_azure_native.certificateregistration.v20200601')
v20200901 = _utilities.lazy_import('pulumi_azure_native.certificateregistration.v20200901')
v20201001 = _utilities.lazy_import('pulumi_azure_native.certificateregistration.v20201001')
v20201201 = _utilities.lazy_import('pulumi_azure_native.certificateregistration.v20201201')
