// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package latest

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi-azure-native/sdk/go/azure"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "azure-native:compute/latest:AvailabilitySet":
		r = &AvailabilitySet{}
	case "azure-native:compute/latest:CloudService":
		r = &CloudService{}
	case "azure-native:compute/latest:DedicatedHost":
		r = &DedicatedHost{}
	case "azure-native:compute/latest:DedicatedHostGroup":
		r = &DedicatedHostGroup{}
	case "azure-native:compute/latest:Disk":
		r = &Disk{}
	case "azure-native:compute/latest:DiskAccess":
		r = &DiskAccess{}
	case "azure-native:compute/latest:DiskAccessAPrivateEndpointConnection":
		r = &DiskAccessAPrivateEndpointConnection{}
	case "azure-native:compute/latest:DiskEncryptionSet":
		r = &DiskEncryptionSet{}
	case "azure-native:compute/latest:Gallery":
		r = &Gallery{}
	case "azure-native:compute/latest:GalleryApplication":
		r = &GalleryApplication{}
	case "azure-native:compute/latest:GalleryApplicationVersion":
		r = &GalleryApplicationVersion{}
	case "azure-native:compute/latest:GalleryImage":
		r = &GalleryImage{}
	case "azure-native:compute/latest:GalleryImageVersion":
		r = &GalleryImageVersion{}
	case "azure-native:compute/latest:Image":
		r = &Image{}
	case "azure-native:compute/latest:ProximityPlacementGroup":
		r = &ProximityPlacementGroup{}
	case "azure-native:compute/latest:Snapshot":
		r = &Snapshot{}
	case "azure-native:compute/latest:SshPublicKey":
		r = &SshPublicKey{}
	case "azure-native:compute/latest:VirtualMachine":
		r = &VirtualMachine{}
	case "azure-native:compute/latest:VirtualMachineExtension":
		r = &VirtualMachineExtension{}
	case "azure-native:compute/latest:VirtualMachineRunCommandByVirtualMachine":
		r = &VirtualMachineRunCommandByVirtualMachine{}
	case "azure-native:compute/latest:VirtualMachineScaleSet":
		r = &VirtualMachineScaleSet{}
	case "azure-native:compute/latest:VirtualMachineScaleSetExtension":
		r = &VirtualMachineScaleSetExtension{}
	case "azure-native:compute/latest:VirtualMachineScaleSetVM":
		r = &VirtualMachineScaleSetVM{}
	case "azure-native:compute/latest:VirtualMachineScaleSetVMExtension":
		r = &VirtualMachineScaleSetVMExtension{}
	case "azure-native:compute/latest:VirtualMachineScaleSetVMRunCommand":
		r = &VirtualMachineScaleSetVMRunCommand{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

func init() {
	version, err := azure.PkgVersion()
	if err != nil {
		fmt.Println("failed to determine package version. defaulting to v1: %v", err)
	}
	pulumi.RegisterResourceModule(
		"azure-native",
		"compute/latest",
		&module{version},
	)
}
