# coding=utf-8
# *** WARNING: this file was generated by the Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from .. import _utilities
import typing
from pulumi._utils import _lazy_import
# Export this package's modules as members:
from ._enums import *
from .get_job import *
from .get_job_collection import *
from .job import *
from .job_collection import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_azure_native.scheduler.v20140801preview as v20140801preview
    import pulumi_azure_native.scheduler.v20160101 as v20160101
    import pulumi_azure_native.scheduler.v20160301 as v20160301
else:
    v20140801preview = _lazy_import('pulumi_azure_native.scheduler.v20140801preview')
    v20160101 = _lazy_import('pulumi_azure_native.scheduler.v20160101')
    v20160301 = _lazy_import('pulumi_azure_native.scheduler.v20160301')

