# coding=utf-8
# *** WARNING: this file was generated by the Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from .. import _utilities
import typing
from pulumi._utils import _lazy_import
# Export this package's modules as members:
from ._enums import *
from .application import *
from .application_type import *
from .application_type_version import *
from .cluster import *
from .get_application import *
from .get_application_type import *
from .get_application_type_version import *
from .get_cluster import *
from .get_managed_cluster import *
from .get_node_type import *
from .get_service import *
from .list_list_upgradable_version_post import *
from .managed_cluster import *
from .node_type import *
from .service import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_azure_native.servicefabric.v20160901 as v20160901
    import pulumi_azure_native.servicefabric.v20170701preview as v20170701preview
    import pulumi_azure_native.servicefabric.v20180201 as v20180201
    import pulumi_azure_native.servicefabric.v20190301 as v20190301
    import pulumi_azure_native.servicefabric.v20190301preview as v20190301preview
    import pulumi_azure_native.servicefabric.v20190601preview as v20190601preview
    import pulumi_azure_native.servicefabric.v20191101preview as v20191101preview
    import pulumi_azure_native.servicefabric.v20200101preview as v20200101preview
    import pulumi_azure_native.servicefabric.v20200301 as v20200301
    import pulumi_azure_native.servicefabric.v20201201preview as v20201201preview
else:
    v20160901 = _lazy_import('pulumi_azure_native.servicefabric.v20160901')
    v20170701preview = _lazy_import('pulumi_azure_native.servicefabric.v20170701preview')
    v20180201 = _lazy_import('pulumi_azure_native.servicefabric.v20180201')
    v20190301 = _lazy_import('pulumi_azure_native.servicefabric.v20190301')
    v20190301preview = _lazy_import('pulumi_azure_native.servicefabric.v20190301preview')
    v20190601preview = _lazy_import('pulumi_azure_native.servicefabric.v20190601preview')
    v20191101preview = _lazy_import('pulumi_azure_native.servicefabric.v20191101preview')
    v20200101preview = _lazy_import('pulumi_azure_native.servicefabric.v20200101preview')
    v20200301 = _lazy_import('pulumi_azure_native.servicefabric.v20200301')
    v20201201preview = _lazy_import('pulumi_azure_native.servicefabric.v20201201preview')

